# CMake generated Testfile for 
# Source directory: /home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-source/avs-device-sdk/AFML/test
# Build directory: /home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(AudioActivityTrackerTest.noActivityUpdate "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/AudioActivityTrackerTest" "--gtest_filter=AudioActivityTrackerTest.noActivityUpdate")
add_test(AudioActivityTrackerTest.emptyActivityUpdate "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/AudioActivityTrackerTest" "--gtest_filter=AudioActivityTrackerTest.emptyActivityUpdate")
add_test(AudioActivityTrackerTest.oneActiveChannel "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/AudioActivityTrackerTest" "--gtest_filter=AudioActivityTrackerTest.oneActiveChannel")
add_test(AudioActivityTrackerTest.oneActiveChannelWithAIPAsInterface "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/AudioActivityTrackerTest" "--gtest_filter=AudioActivityTrackerTest.oneActiveChannelWithAIPAsInterface")
add_test(AudioActivityTrackerTest.oneActiveChannelWithDefaultAndAIPAsInterfaces "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/AudioActivityTrackerTest" "--gtest_filter=AudioActivityTrackerTest.oneActiveChannelWithDefaultAndAIPAsInterfaces")
add_test(AudioActivityTrackerTest.twoActiveChannels "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/AudioActivityTrackerTest" "--gtest_filter=AudioActivityTrackerTest.twoActiveChannels")
add_test(AudioActivityTrackerTest.oneActiveOneIdleChannels "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/AudioActivityTrackerTest" "--gtest_filter=AudioActivityTrackerTest.oneActiveOneIdleChannels")
add_test(FocusManagerTest.acquireInvalidChannelName "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/FocusManagerTest" "--gtest_filter=FocusManagerTest.acquireInvalidChannelName")
add_test(FocusManagerTest.acquireChannelWithNoOtherChannelsActive "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/FocusManagerTest" "--gtest_filter=FocusManagerTest.acquireChannelWithNoOtherChannelsActive")
add_test(FocusManagerTest.acquireLowerPriorityChannelWithOneHigherPriorityChannelTaken "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/FocusManagerTest" "--gtest_filter=FocusManagerTest.acquireLowerPriorityChannelWithOneHigherPriorityChannelTaken")
add_test(FocusManagerTest.aquireLowerPriorityChannelWithTwoHigherPriorityChannelsTaken "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/FocusManagerTest" "--gtest_filter=FocusManagerTest.aquireLowerPriorityChannelWithTwoHigherPriorityChannelsTaken")
add_test(FocusManagerTest.acquireHigherPriorityChannelWithOneLowerPriorityChannelTaken "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/FocusManagerTest" "--gtest_filter=FocusManagerTest.acquireHigherPriorityChannelWithOneLowerPriorityChannelTaken")
add_test(FocusManagerTest.kickOutActivityOnSameChannel "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/FocusManagerTest" "--gtest_filter=FocusManagerTest.kickOutActivityOnSameChannel")
add_test(FocusManagerTest.simpleReleaseChannel "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/FocusManagerTest" "--gtest_filter=FocusManagerTest.simpleReleaseChannel")
add_test(FocusManagerTest.simpleReleaseChannelWithIncorrectObserver "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/FocusManagerTest" "--gtest_filter=FocusManagerTest.simpleReleaseChannelWithIncorrectObserver")
add_test(FocusManagerTest.releaseForegroundChannelWhileBackgroundChannelTaken "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/FocusManagerTest" "--gtest_filter=FocusManagerTest.releaseForegroundChannelWhileBackgroundChannelTaken")
add_test(FocusManagerTest.simpleNonTargetedStop "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/FocusManagerTest" "--gtest_filter=FocusManagerTest.simpleNonTargetedStop")
add_test(FocusManagerTest.threeNonTargetedStopsWithThreeActivitiesHappening "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/FocusManagerTest" "--gtest_filter=FocusManagerTest.threeNonTargetedStopsWithThreeActivitiesHappening")
add_test(FocusManagerTest.stopForegroundActivityAndAcquireDifferentChannel "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/FocusManagerTest" "--gtest_filter=FocusManagerTest.stopForegroundActivityAndAcquireDifferentChannel")
add_test(FocusManagerTest.stopForegroundActivityAndAcquireSameChannel "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/FocusManagerTest" "--gtest_filter=FocusManagerTest.stopForegroundActivityAndAcquireSameChannel")
add_test(FocusManagerTest.releaseBackgroundChannelWhileTwoChannelsTaken "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/FocusManagerTest" "--gtest_filter=FocusManagerTest.releaseBackgroundChannelWhileTwoChannelsTaken")
add_test(FocusManagerTest.kickOutActivityOnSameChannelWhileOtherChannelsActive "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/FocusManagerTest" "--gtest_filter=FocusManagerTest.kickOutActivityOnSameChannelWhileOtherChannelsActive")
add_test(FocusManagerTest.addObserver "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/FocusManagerTest" "--gtest_filter=FocusManagerTest.addObserver")
add_test(FocusManagerTest.removeObserver "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/FocusManagerTest" "--gtest_filter=FocusManagerTest.removeObserver")
add_test(FocusManagerTest.activityTracker "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/FocusManagerTest" "--gtest_filter=FocusManagerTest.activityTracker")
add_test(ChannelTest.getName "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/FocusManagerTest" "--gtest_filter=ChannelTest.getName")
add_test(ChannelTest.getPriority "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/FocusManagerTest" "--gtest_filter=ChannelTest.getPriority")
add_test(ChannelTest.setObserverThenSetFocus "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/FocusManagerTest" "--gtest_filter=ChannelTest.setObserverThenSetFocus")
add_test(ChannelTest.priorityComparison "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/FocusManagerTest" "--gtest_filter=ChannelTest.priorityComparison")
add_test(ChannelTest.hasObserver "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/FocusManagerTest" "--gtest_filter=ChannelTest.hasObserver")
add_test(ChannelTest.getTimeAtIdle "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/FocusManagerTest" "--gtest_filter=ChannelTest.getTimeAtIdle")
add_test(VisualActivityTrackerTest.noActivityUpdate "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/VisualActivityTrackerTest" "--gtest_filter=VisualActivityTrackerTest.noActivityUpdate")
add_test(VisualActivityTrackerTest.emptyActivityUpdate "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/VisualActivityTrackerTest" "--gtest_filter=VisualActivityTrackerTest.emptyActivityUpdate")
add_test(VisualActivityTrackerTest.oneIdleChannel "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/VisualActivityTrackerTest" "--gtest_filter=VisualActivityTrackerTest.oneIdleChannel")
add_test(VisualActivityTrackerTest.oneActiveChannel "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/VisualActivityTrackerTest" "--gtest_filter=VisualActivityTrackerTest.oneActiveChannel")
add_test(VisualActivityTrackerTest.invalidChannelActivityUpdate "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/VisualActivityTrackerTest" "--gtest_filter=VisualActivityTrackerTest.invalidChannelActivityUpdate")
add_test(VisualActivityTrackerTest.validChannelTwoActivityUpdates "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/AFML/test/VisualActivityTrackerTest" "--gtest_filter=VisualActivityTrackerTest.validChannelTwoActivityUpdates")
