# CMake generated Testfile for 
# Source directory: /home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/SpeakerManager/test
# Build directory: /home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/SpeakerManager/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(SpeakerManagerTest.testNullContextManager "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/SpeakerManager/test/SpeakerManagerTest" "--gtest_filter=SpeakerManagerTest.testNullContextManager")
add_test(SpeakerManagerTest.testNullMessageSender "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/SpeakerManager/test/SpeakerManagerTest" "--gtest_filter=SpeakerManagerTest.testNullMessageSender")
add_test(SpeakerManagerTest.testNullExceptionSender "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/SpeakerManager/test/SpeakerManagerTest" "--gtest_filter=SpeakerManagerTest.testNullExceptionSender")
add_test(SpeakerManagerTest.testNoSpeakers "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/SpeakerManager/test/SpeakerManagerTest" "--gtest_filter=SpeakerManagerTest.testNoSpeakers")
add_test(SpeakerManagerTest.testContextManagerSetStateConstructor "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/SpeakerManager/test/SpeakerManagerTest" "--gtest_filter=SpeakerManagerTest.testContextManagerSetStateConstructor")
add_test(SpeakerManagerTest.testSetVolumeUnderBounds "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/SpeakerManager/test/SpeakerManagerTest" "--gtest_filter=SpeakerManagerTest.testSetVolumeUnderBounds")
add_test(SpeakerManagerTest.testSetVolumeOverBounds "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/SpeakerManager/test/SpeakerManagerTest" "--gtest_filter=SpeakerManagerTest.testSetVolumeOverBounds")
add_test(SpeakerManagerTest.testAdjustVolumeUnderBounds "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/SpeakerManager/test/SpeakerManagerTest" "--gtest_filter=SpeakerManagerTest.testAdjustVolumeUnderBounds")
add_test(SpeakerManagerTest.testAdjustVolumeOverBounds "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/SpeakerManager/test/SpeakerManagerTest" "--gtest_filter=SpeakerManagerTest.testAdjustVolumeOverBounds")
add_test(SpeakerManagerTest.testSetVolumeOutOfSync "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/SpeakerManager/test/SpeakerManagerTest" "--gtest_filter=SpeakerManagerTest.testSetVolumeOutOfSync")
add_test(SpeakerManagerTest.testAdjustVolumeOutOfSync "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/SpeakerManager/test/SpeakerManagerTest" "--gtest_filter=SpeakerManagerTest.testAdjustVolumeOutOfSync")
add_test(SpeakerManagerTest.testSetMuteOutOfSync "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/SpeakerManager/test/SpeakerManagerTest" "--gtest_filter=SpeakerManagerTest.testSetMuteOutOfSync")
add_test(SpeakerManagerTest.testGetSpeakerSettingsSpeakersOutOfSync "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/SpeakerManager/test/SpeakerManagerTest" "--gtest_filter=SpeakerManagerTest.testGetSpeakerSettingsSpeakersOutOfSync")
add_test(SpeakerManagerTest.testGetConfiguration "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/SpeakerManager/test/SpeakerManagerTest" "--gtest_filter=SpeakerManagerTest.testGetConfiguration")
add_test(SpeakerManagerTest.testAddNullObserver "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/SpeakerManager/test/SpeakerManagerTest" "--gtest_filter=SpeakerManagerTest.testAddNullObserver")
add_test(SpeakerManagerTest.testRemoveSpeakerManagerObserver "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/SpeakerManager/test/SpeakerManagerTest" "--gtest_filter=SpeakerManagerTest.testRemoveSpeakerManagerObserver")
add_test(SpeakerManagerTest.testRemoveNullObserver "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/SpeakerManager/test/SpeakerManagerTest" "--gtest_filter=SpeakerManagerTest.testRemoveNullObserver")
add_test(*/SpeakerManagerTest.testSetVolume/* "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/SpeakerManager/test/SpeakerManagerTest" "--gtest_filter=*/SpeakerManagerTest.testSetVolume/*")
add_test(*/SpeakerManagerTest.testAdjustVolume/* "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/SpeakerManager/test/SpeakerManagerTest" "--gtest_filter=*/SpeakerManagerTest.testAdjustVolume/*")
add_test(*/SpeakerManagerTest.testSetMute/* "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/SpeakerManager/test/SpeakerManagerTest" "--gtest_filter=*/SpeakerManagerTest.testSetMute/*")
add_test(*/SpeakerManagerTest.testGetSpeakerSettings/* "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/SpeakerManager/test/SpeakerManagerTest" "--gtest_filter=*/SpeakerManagerTest.testGetSpeakerSettings/*")
add_test(*/SpeakerManagerTest.testSetVolumeDirective/* "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/SpeakerManager/test/SpeakerManagerTest" "--gtest_filter=*/SpeakerManagerTest.testSetVolumeDirective/*")
add_test(*/SpeakerManagerTest.testAdjustVolumeDirective/* "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/SpeakerManager/test/SpeakerManagerTest" "--gtest_filter=*/SpeakerManagerTest.testAdjustVolumeDirective/*")
add_test(*/SpeakerManagerTest.testSetMuteDirective/* "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/SpeakerManager/test/SpeakerManagerTest" "--gtest_filter=*/SpeakerManagerTest.testSetMuteDirective/*")
