# CMake generated Testfile for 
# Source directory: /home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/Bluetooth/test
# Build directory: /home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(SQLiteBluetoothStorageTest.createInvalidConfigurationRoot "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test/SQLiteBluetoothStorageTest" "--gtest_filter=SQLiteBluetoothStorageTest.createInvalidConfigurationRoot")
add_test(SQLiteBluetoothStorageTest.createValidConfigurationRoot "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test/SQLiteBluetoothStorageTest" "--gtest_filter=SQLiteBluetoothStorageTest.createValidConfigurationRoot")
add_test(SQLiteBluetoothStorageTest.createDatabaseSucceeds "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test/SQLiteBluetoothStorageTest" "--gtest_filter=SQLiteBluetoothStorageTest.createDatabaseSucceeds")
add_test(SQLiteBluetoothStorageTest.createExistingDatabaseFails "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test/SQLiteBluetoothStorageTest" "--gtest_filter=SQLiteBluetoothStorageTest.createExistingDatabaseFails")
add_test(SQLiteBluetoothStorageTest.openExistingDatabaseSucceeds "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test/SQLiteBluetoothStorageTest" "--gtest_filter=SQLiteBluetoothStorageTest.openExistingDatabaseSucceeds")
add_test(SQLiteBluetoothStorageTest.clearOnOneRowSucceeds "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test/SQLiteBluetoothStorageTest" "--gtest_filter=SQLiteBluetoothStorageTest.clearOnOneRowSucceeds")
add_test(SQLiteBluetoothStorageTest.clearOnMultipleRowsSucceeds "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test/SQLiteBluetoothStorageTest" "--gtest_filter=SQLiteBluetoothStorageTest.clearOnMultipleRowsSucceeds")
add_test(SQLiteBluetoothStorageTest.clearOnEmptySucceeds "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test/SQLiteBluetoothStorageTest" "--gtest_filter=SQLiteBluetoothStorageTest.clearOnEmptySucceeds")
add_test(SQLiteBluetoothStorageTest.getUuidWithOneSucceeds "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test/SQLiteBluetoothStorageTest" "--gtest_filter=SQLiteBluetoothStorageTest.getUuidWithOneSucceeds")
add_test(SQLiteBluetoothStorageTest.getUuidWithMultipleSucceeds "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test/SQLiteBluetoothStorageTest" "--gtest_filter=SQLiteBluetoothStorageTest.getUuidWithMultipleSucceeds")
add_test(SQLiteBluetoothStorageTest.getUuidNoMatchingFails "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test/SQLiteBluetoothStorageTest" "--gtest_filter=SQLiteBluetoothStorageTest.getUuidNoMatchingFails")
add_test(SQLiteBluetoothStorageTest.getMacWithOneSucceeds "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test/SQLiteBluetoothStorageTest" "--gtest_filter=SQLiteBluetoothStorageTest.getMacWithOneSucceeds")
add_test(SQLiteBluetoothStorageTest.getMacWithMultipleSucceeds "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test/SQLiteBluetoothStorageTest" "--gtest_filter=SQLiteBluetoothStorageTest.getMacWithMultipleSucceeds")
add_test(SQLiteBluetoothStorageTest.getMacNoMatchingFails "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test/SQLiteBluetoothStorageTest" "--gtest_filter=SQLiteBluetoothStorageTest.getMacNoMatchingFails")
add_test(SQLiteBluetoothStorageTest.getMacToUuidWithOneRowSucceeds "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test/SQLiteBluetoothStorageTest" "--gtest_filter=SQLiteBluetoothStorageTest.getMacToUuidWithOneRowSucceeds")
add_test(SQLiteBluetoothStorageTest.getMacToUuidWithMultipleRowsSucceeds "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test/SQLiteBluetoothStorageTest" "--gtest_filter=SQLiteBluetoothStorageTest.getMacToUuidWithMultipleRowsSucceeds")
add_test(SQLiteBluetoothStorageTest.getMacToUuidWithEmptySucceeds "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test/SQLiteBluetoothStorageTest" "--gtest_filter=SQLiteBluetoothStorageTest.getMacToUuidWithEmptySucceeds")
add_test(SQLiteBluetoothStorageTest.getUuidToMacWithOneRowSucceeds "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test/SQLiteBluetoothStorageTest" "--gtest_filter=SQLiteBluetoothStorageTest.getUuidToMacWithOneRowSucceeds")
add_test(SQLiteBluetoothStorageTest.getUuidToMacWithMultipleRowsSucceeds "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test/SQLiteBluetoothStorageTest" "--gtest_filter=SQLiteBluetoothStorageTest.getUuidToMacWithMultipleRowsSucceeds")
add_test(SQLiteBluetoothStorageTest.getUuidToMacWithEmptySucceeds "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test/SQLiteBluetoothStorageTest" "--gtest_filter=SQLiteBluetoothStorageTest.getUuidToMacWithEmptySucceeds")
add_test(SQLiteBluetoothStorageTest.getOrderedMacAscending "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test/SQLiteBluetoothStorageTest" "--gtest_filter=SQLiteBluetoothStorageTest.getOrderedMacAscending")
add_test(SQLiteBluetoothStorageTest.getOrderedMacDescending "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test/SQLiteBluetoothStorageTest" "--gtest_filter=SQLiteBluetoothStorageTest.getOrderedMacDescending")
add_test(SQLiteBluetoothStorageTest.insertByMacSucceeds "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test/SQLiteBluetoothStorageTest" "--gtest_filter=SQLiteBluetoothStorageTest.insertByMacSucceeds")
add_test(SQLiteBluetoothStorageTest.insertByMacDuplicateFails "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test/SQLiteBluetoothStorageTest" "--gtest_filter=SQLiteBluetoothStorageTest.insertByMacDuplicateFails")
add_test(SQLiteBluetoothStorageTest.insertByMacOverwriteSucceeds "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test/SQLiteBluetoothStorageTest" "--gtest_filter=SQLiteBluetoothStorageTest.insertByMacOverwriteSucceeds")
add_test(SQLiteBluetoothStorageTest.removeExistingSucceeds "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test/SQLiteBluetoothStorageTest" "--gtest_filter=SQLiteBluetoothStorageTest.removeExistingSucceeds")
add_test(SQLiteBluetoothStorageTest.removeNonExistingSucceeds "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Bluetooth/test/SQLiteBluetoothStorageTest" "--gtest_filter=SQLiteBluetoothStorageTest.removeNonExistingSucceeds")
