# CMake generated Testfile for 
# Source directory: /home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/System/test
# Build directory: /home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/System/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(EndpointHandlerTest.createSuccessfully "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/System/test/EndpointHandlerTest" "--gtest_filter=EndpointHandlerTest.createSuccessfully")
add_test(EndpointHandlerTest.createWithError "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/System/test/EndpointHandlerTest" "--gtest_filter=EndpointHandlerTest.createWithError")
add_test(EndpointHandlerTest.handleDirectiveProperly "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/System/test/EndpointHandlerTest" "--gtest_filter=EndpointHandlerTest.handleDirectiveProperly")
add_test(SoftwareInfoSenderTest.createFailedInvalidFirmwareVersion "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/System/test/SoftwareInfoTest" "--gtest_filter=SoftwareInfoSenderTest.createFailedInvalidFirmwareVersion")
add_test(SoftwareInfoSenderTest.createSuccessWithsendSoftwareInfoUponConnectFalse "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/System/test/SoftwareInfoTest" "--gtest_filter=SoftwareInfoSenderTest.createSuccessWithsendSoftwareInfoUponConnectFalse")
add_test(SoftwareInfoSenderTest.createSuccessWithObserverNull "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/System/test/SoftwareInfoTest" "--gtest_filter=SoftwareInfoSenderTest.createSuccessWithObserverNull")
add_test(SoftwareInfoSenderTest.createFailedConnectionNull "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/System/test/SoftwareInfoTest" "--gtest_filter=SoftwareInfoSenderTest.createFailedConnectionNull")
add_test(SoftwareInfoSenderTest.createFailedMessageSenderNull "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/System/test/SoftwareInfoTest" "--gtest_filter=SoftwareInfoSenderTest.createFailedMessageSenderNull")
add_test(SoftwareInfoSenderTest.createFailedExceptionEncounteredSenderNull "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/System/test/SoftwareInfoTest" "--gtest_filter=SoftwareInfoSenderTest.createFailedExceptionEncounteredSenderNull")
add_test(SoftwareInfoSenderTest.noSoftwareInfoEventSentByDefault "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/System/test/SoftwareInfoTest" "--gtest_filter=SoftwareInfoSenderTest.noSoftwareInfoEventSentByDefault")
add_test(SoftwareInfoSenderTest.nothingSentBeforeConnected "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/System/test/SoftwareInfoTest" "--gtest_filter=SoftwareInfoSenderTest.nothingSentBeforeConnected")
add_test(SoftwareInfoSenderTest.softwareInfoSentUponConnectIfSendSetTrueBeforeConnect "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/System/test/SoftwareInfoTest" "--gtest_filter=SoftwareInfoSenderTest.softwareInfoSentUponConnectIfSendSetTrueBeforeConnect")
add_test(SoftwareInfoSenderTest.reportSoftwareInfoReceived "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/System/test/SoftwareInfoTest" "--gtest_filter=SoftwareInfoSenderTest.reportSoftwareInfoReceived")
add_test(SoftwareInfoSenderTest.reportSoftwareInfoCancellsPreviousDirective "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/System/test/SoftwareInfoTest" "--gtest_filter=SoftwareInfoSenderTest.reportSoftwareInfoCancellsPreviousDirective")
add_test(SoftwareInfoSenderTest.delayedReportSoftwareInfoNotifiesOnce "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/System/test/SoftwareInfoTest" "--gtest_filter=SoftwareInfoSenderTest.delayedReportSoftwareInfoNotifiesOnce")
add_test(SoftwareInfoSenderTest.verifySendRetries "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/System/test/SoftwareInfoTest" "--gtest_filter=SoftwareInfoSenderTest.verifySendRetries")
add_test(SoftwareInfoSenderTest.setInvalidFirmwareVersion "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/System/test/SoftwareInfoTest" "--gtest_filter=SoftwareInfoSenderTest.setInvalidFirmwareVersion")
add_test(SoftwareInfoSenderTest.setFirmwareVersionCancellsPreviousSetting "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/System/test/SoftwareInfoTest" "--gtest_filter=SoftwareInfoSenderTest.setFirmwareVersionCancellsPreviousSetting")
add_test(UserInactivityMonitorTest.createSuccessfully "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/System/test/UserInactivityMonitorTest" "--gtest_filter=UserInactivityMonitorTest.createSuccessfully")
add_test(UserInactivityMonitorTest.createWithError "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/System/test/UserInactivityMonitorTest" "--gtest_filter=UserInactivityMonitorTest.createWithError")
add_test(UserInactivityMonitorTest.handleDirectiveProperly "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/System/test/UserInactivityMonitorTest" "--gtest_filter=UserInactivityMonitorTest.handleDirectiveProperly")
add_test(UserInactivityMonitorTest.sendMultipleReports "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/System/test/UserInactivityMonitorTest" "--gtest_filter=UserInactivityMonitorTest.sendMultipleReports")
add_test(UserInactivityMonitorTest.verifyInactivityTime "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/System/test/UserInactivityMonitorTest" "--gtest_filter=UserInactivityMonitorTest.verifyInactivityTime")
add_test(UserInactivityMonitorTest.sendMultipleReportsWithReset "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/System/test/UserInactivityMonitorTest" "--gtest_filter=UserInactivityMonitorTest.sendMultipleReportsWithReset")
