# CMake generated Testfile for 
# Source directory: /home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/TemplateRuntime/test
# Build directory: /home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/TemplateRuntime/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(TemplateRuntimeTest.testNullAudioPlayerInterface "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/TemplateRuntime/test/TemplateRuntimeTest" "--gtest_filter=TemplateRuntimeTest.testNullAudioPlayerInterface")
add_test(TemplateRuntimeTest.testNullFocusManagerInterface "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/TemplateRuntime/test/TemplateRuntimeTest" "--gtest_filter=TemplateRuntimeTest.testNullFocusManagerInterface")
add_test(TemplateRuntimeTest.testNullExceptionSender "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/TemplateRuntime/test/TemplateRuntimeTest" "--gtest_filter=TemplateRuntimeTest.testNullExceptionSender")
add_test(TemplateRuntimeTest.testAudioPlayerAddRemoveObserver "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/TemplateRuntime/test/TemplateRuntimeTest" "--gtest_filter=TemplateRuntimeTest.testAudioPlayerAddRemoveObserver")
add_test(TemplateRuntimeTest.testUnknownDirective "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/TemplateRuntime/test/TemplateRuntimeTest" "--gtest_filter=TemplateRuntimeTest.testUnknownDirective")
add_test(TemplateRuntimeTest.testRenderTemplateDirective "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/TemplateRuntime/test/TemplateRuntimeTest" "--gtest_filter=TemplateRuntimeTest.testRenderTemplateDirective")
add_test(TemplateRuntimeTest.testHandleDirectiveImmediately "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/TemplateRuntime/test/TemplateRuntimeTest" "--gtest_filter=TemplateRuntimeTest.testHandleDirectiveImmediately")
add_test(TemplateRuntimeTest.testRenderPlayerInfoDirectiveBefore "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/TemplateRuntime/test/TemplateRuntimeTest" "--gtest_filter=TemplateRuntimeTest.testRenderPlayerInfoDirectiveBefore")
add_test(TemplateRuntimeTest.testRenderPlayerInfoDirectiveAfter "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/TemplateRuntime/test/TemplateRuntimeTest" "--gtest_filter=TemplateRuntimeTest.testRenderPlayerInfoDirectiveAfter")
add_test(TemplateRuntimeTest.testRenderPlayerInfoDirectiveWithoutAudioItemId "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/TemplateRuntime/test/TemplateRuntimeTest" "--gtest_filter=TemplateRuntimeTest.testRenderPlayerInfoDirectiveWithoutAudioItemId")
add_test(TemplateRuntimeTest.testMalformedRenderPlayerInfoDirective "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/TemplateRuntime/test/TemplateRuntimeTest" "--gtest_filter=TemplateRuntimeTest.testMalformedRenderPlayerInfoDirective")
add_test(TemplateRuntimeTest.testRenderPlayerInfoDirectiveDifferentAudioItemId "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/TemplateRuntime/test/TemplateRuntimeTest" "--gtest_filter=TemplateRuntimeTest.testRenderPlayerInfoDirectiveDifferentAudioItemId")
add_test(TemplateRuntimeTest.testRenderPlayerInfoDirectiveAudioStateUpdate "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/TemplateRuntime/test/TemplateRuntimeTest" "--gtest_filter=TemplateRuntimeTest.testRenderPlayerInfoDirectiveAudioStateUpdate")
add_test(TemplateRuntimeTest.testFocusNone "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/TemplateRuntime/test/TemplateRuntimeTest" "--gtest_filter=TemplateRuntimeTest.testFocusNone")
add_test(TemplateRuntimeTest.testDisplayCardCleared "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/TemplateRuntime/test/TemplateRuntimeTest" "--gtest_filter=TemplateRuntimeTest.testDisplayCardCleared")
add_test(TemplateRuntimeTest.testReacquireChannel "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/TemplateRuntime/test/TemplateRuntimeTest" "--gtest_filter=TemplateRuntimeTest.testReacquireChannel")
