# CMake generated Testfile for 
# Source directory: /home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-source/avs-device-sdk/CapabilityAgents/Alerts/test
# Build directory: /home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(AlarmAlertTest.defaultAudio "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlarmAlertTest" "--gtest_filter=AlarmAlertTest.defaultAudio")
add_test(AlarmAlertTest.shortAudio "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlarmAlertTest" "--gtest_filter=AlarmAlertTest.shortAudio")
add_test(AlarmAlertTest.testGetTypeName "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlarmAlertTest" "--gtest_filter=AlarmAlertTest.testGetTypeName")
add_test(AlertSchedulerTest.initialize "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertSchedulerTest" "--gtest_filter=AlertSchedulerTest.initialize")
add_test(AlertSchedulerTest.updateGetFocus "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertSchedulerTest" "--gtest_filter=AlertSchedulerTest.updateGetFocus")
add_test(AlertSchedulerTest.scheduleAlert "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertSchedulerTest" "--gtest_filter=AlertSchedulerTest.scheduleAlert")
add_test(AlertSchedulerTest.snoozeAlert "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertSchedulerTest" "--gtest_filter=AlertSchedulerTest.snoozeAlert")
add_test(AlertSchedulerTest.deleteAlert "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertSchedulerTest" "--gtest_filter=AlertSchedulerTest.deleteAlert")
add_test(AlertSchedulerTest.isAlertActive "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertSchedulerTest" "--gtest_filter=AlertSchedulerTest.isAlertActive")
add_test(AlertSchedulerTest.getContextInfo "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertSchedulerTest" "--gtest_filter=AlertSchedulerTest.getContextInfo")
add_test(AlertSchedulerTest.onLocalStop "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertSchedulerTest" "--gtest_filter=AlertSchedulerTest.onLocalStop")
add_test(AlertSchedulerTest.clearData "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertSchedulerTest" "--gtest_filter=AlertSchedulerTest.clearData")
add_test(AlertSchedulerTest.clearDataLogout "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertSchedulerTest" "--gtest_filter=AlertSchedulerTest.clearDataLogout")
add_test(AlertSchedulerTest.shutdown "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertSchedulerTest" "--gtest_filter=AlertSchedulerTest.shutdown")
add_test(AlertSchedulerTest.onAlertStateChangeStartedInactiveAlert "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertSchedulerTest" "--gtest_filter=AlertSchedulerTest.onAlertStateChangeStartedInactiveAlert")
add_test(AlertSchedulerTest.onAlertStateChangeStartedActiveAlert "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertSchedulerTest" "--gtest_filter=AlertSchedulerTest.onAlertStateChangeStartedActiveAlert")
add_test(AlertSchedulerTest.onAlertStateChangeStopped "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertSchedulerTest" "--gtest_filter=AlertSchedulerTest.onAlertStateChangeStopped")
add_test(AlertSchedulerTest.onAlertStateChangeCompleted "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertSchedulerTest" "--gtest_filter=AlertSchedulerTest.onAlertStateChangeCompleted")
add_test(AlertSchedulerTest.onAlertStateChangeSnoozed "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertSchedulerTest" "--gtest_filter=AlertSchedulerTest.onAlertStateChangeSnoozed")
add_test(AlertSchedulerTest.onAlertStateChangeErrorActiveAlert "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertSchedulerTest" "--gtest_filter=AlertSchedulerTest.onAlertStateChangeErrorActiveAlert")
add_test(AlertSchedulerTest.onAlertStateChangeErrorInactiveAlert "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertSchedulerTest" "--gtest_filter=AlertSchedulerTest.onAlertStateChangeErrorInactiveAlert")
add_test(AlertTest.defaultAudio "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertTest" "--gtest_filter=AlertTest.defaultAudio")
add_test(AlertTest.defaultShortAudio "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertTest" "--gtest_filter=AlertTest.defaultShortAudio")
add_test(AlertTest.testParseFromJsonHappyCase "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertTest" "--gtest_filter=AlertTest.testParseFromJsonHappyCase")
add_test(AlertTest.testParseFromJsonMissingToken "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertTest" "--gtest_filter=AlertTest.testParseFromJsonMissingToken")
add_test(AlertTest.testParseFromJsonMissingSchedTime "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertTest" "--gtest_filter=AlertTest.testParseFromJsonMissingSchedTime")
add_test(AlertTest.testParseFromJsonBadSchedTimeFormat "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertTest" "--gtest_filter=AlertTest.testParseFromJsonBadSchedTimeFormat")
add_test(AlertTest.testSetStateActive "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertTest" "--gtest_filter=AlertTest.testSetStateActive")
add_test(AlertTest.testDeactivate "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertTest" "--gtest_filter=AlertTest.testDeactivate")
add_test(AlertTest.testSetTimeISO8601 "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertTest" "--gtest_filter=AlertTest.testSetTimeISO8601")
add_test(AlertTest.testSnoozeBadTime "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertTest" "--gtest_filter=AlertTest.testSnoozeBadTime")
add_test(AlertTest.testSnoozeHappyCase "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertTest" "--gtest_filter=AlertTest.testSnoozeHappyCase")
add_test(AlertTest.testSetLoopCountNegative "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertTest" "--gtest_filter=AlertTest.testSetLoopCountNegative")
add_test(AlertTest.testSetLoopCountHappyCase "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertTest" "--gtest_filter=AlertTest.testSetLoopCountHappyCase")
add_test(AlertTest.testSetLoopPause "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertTest" "--gtest_filter=AlertTest.testSetLoopPause")
add_test(AlertTest.testSetBackgroundAssetId "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertTest" "--gtest_filter=AlertTest.testSetBackgroundAssetId")
add_test(AlertTest.testIsPastDue "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertTest" "--gtest_filter=AlertTest.testIsPastDue")
add_test(AlertTest.testStateToString "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertTest" "--gtest_filter=AlertTest.testStateToString")
add_test(AlertTest.testStopReasonToString "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertTest" "--gtest_filter=AlertTest.testStopReasonToString")
add_test(AlertTest.testParseFromJsonStatusToString "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/AlertTest" "--gtest_filter=AlertTest.testParseFromJsonStatusToString")
add_test(ReminderAlertTest.defaultAudio "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/ReminderAlertTest" "--gtest_filter=ReminderAlertTest.defaultAudio")
add_test(ReminderAlertTest.shortAudio "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/ReminderAlertTest" "--gtest_filter=ReminderAlertTest.shortAudio")
add_test(ReminderAlertTest.testGetTypeName "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/ReminderAlertTest" "--gtest_filter=ReminderAlertTest.testGetTypeName")
add_test(RendererTest.create "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/RendererTest" "--gtest_filter=RendererTest.create")
add_test(RendererTest.start "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/RendererTest" "--gtest_filter=RendererTest.start")
add_test(RendererTest.stop "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/RendererTest" "--gtest_filter=RendererTest.stop")
add_test(RendererTest.stopError "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/RendererTest" "--gtest_filter=RendererTest.stopError")
add_test(RendererTest.onPlaybackStarted "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/RendererTest" "--gtest_filter=RendererTest.onPlaybackStarted")
add_test(RendererTest.onPlaybackStopped "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/RendererTest" "--gtest_filter=RendererTest.onPlaybackStopped")
add_test(RendererTest.onPlaybackFinished "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/RendererTest" "--gtest_filter=RendererTest.onPlaybackFinished")
add_test(RendererTest.onPlaybackFinishedError "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/RendererTest" "--gtest_filter=RendererTest.onPlaybackFinishedError")
add_test(RendererTest.onPlaybackError "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/RendererTest" "--gtest_filter=RendererTest.onPlaybackError")
add_test(RendererTest.emptyURLNonZeroLoopPause "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/RendererTest" "--gtest_filter=RendererTest.emptyURLNonZeroLoopPause")
add_test(TimerAlertTest.defaultAudio "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/TimerAlertTest" "--gtest_filter=TimerAlertTest.defaultAudio")
add_test(TimerAlertTest.shortAudio "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/TimerAlertTest" "--gtest_filter=TimerAlertTest.shortAudio")
add_test(TimerAlertTest.testGetTypeName "/home/junlon2006/workspace/amazon/avs_2rd/sdk-folder/sdk-build/CapabilityAgents/Alerts/test/TimerAlertTest" "--gtest_filter=TimerAlertTest.testGetTypeName")
